

syntax = "proto3";
// rename: proj_config.proto since it includes MaxSizes (not just GP)
import "probes.proto";
import "nanopb.proto";

// When changing number of probes, update NUM_PROBES in ghostProbe.c
message ScanCtl {
  StreamFreq streamFreq = 1;
  SnapFreq snapFreq = 2;
  @PROBE_0_DEFINITION@
  @PROBE_1_DEFINITION@
  @PROBE_2_DEFINITION@
  @PROBE_3_DEFINITION@
  @PROBE_4_DEFINITION@
  @PROBE_5_DEFINITION@
  @PROBE_6_DEFINITION@
  @PROBE_7_DEFINITION@
  @PROBE_8_DEFINITION@
  @PROBE_9_DEFINITION@
}

message ProbeSignal {
  TestPointId id = 1;
  float value = 2;
}
/* An optimization to reduce msg lengths for int types*/
// message probeSignal {
//   oneof signal {
//     intSignal intSig = 1;
//     floatSignal floatSig = 2;
//   }
// }

message ProbeSignals {
  uint32 recordId = 1;
  repeated ProbeSignal probeSignals = 2 [(nanopb).max_count = @GP_NUM_PROBES@];
}

message ManualSnapCtl {}

message Reset {}


/* Standard messages follow */
message Ack {
  fixed32 refCRC = 1;
}


enum ParamOperation {
  CURRENT_VAL = 0;
  GET = 1;
  SET = 2;
}

message TouchParam {
  ParamOperation operation = 1;
  oneof param {
    float paramA = 2;
    int32 paramB = 3;
  }
}

message Log {
  uint32 count = 1;
  string text = 2 [(nanopb).max_size = @LOG_TEXT_MAX_SIZE@ ]; 
  float value = 3;
}

message FirmentErrorTlm {
  uint32 armRxError = 1;
  uint32 dataLost = 2;
  uint32 modeFault = 3;
  uint32 unhandledArmEvent = 4;
  uint32 sendQueueFull = 5;
  uint32 rxQueueFull = 6;
  uint32 encodeFail = 7;
  uint32 decodeFail = 8;
  uint32 crcMismatch = 9;
  uint32 crcComputeFail = 10;
}

message ImageData {
  uint32 pageIndex = 1;
  uint32 pageCount = 2;
  uint32 chunkIndex = 3;
  uint32 chunkCountInPage = 4;
  bytes payload = 5 [(nanopb).max_size = @DATA_MSG_PAYLOAD_SIZE_MAX@ ];
}

enum PageStatusEnum {
  WRITE_FAIL = 0;
  WRITE_SUCCESS = 1;
  // REQUEST_RESEND = 2;  // Placeholder for future chunk resend feature. 
}

message PageStatus {
  uint32 pageIndex = 1;
  PageStatusEnum status = 2;
}

message Version {
  uint32 major = 1;
  uint32 minor = 2;
  uint32 patch = 3;
  uint32 buildId = 4;
  uint32 upTime = 5;
  uint32 pcbId = 6;
}

message Hello {
  uint32 deviceId = 1;
  string project = 2 [(nanopb).max_size = 32 ];
}