/** Generated File Do not Track.
 * Generated by gen-firment.py based on .proto file.
 * Provides first-level handling of received messages.
 * */
#include <fmt_update.h>
#include <fmt_rx.h>
#include <fmt_spi.h>       // fmt_getMsg()
#include <fmt_log.h>       // fmt_sendLog()
#include <ghostProbe.h>    // handleRunScanCtl()
#include <project_comms.h> // all project-specific handlers

void fmt_handleRx(void)
{
  Top incomingMessage;
  if (fmt_getMsg(&incomingMessage))
  {
    switch (incomingMessage.which_sub)
    {
    case Top_Ack_tag:
    {
      Ack subMsg = incomingMessage.sub.Ack;
      break;
    }
      /*--GENERATED CONTENT MARKER--*/
    default:
    }
  }
  else
  { // failed to decode.
    // TODO: figure out why this causes messages to overflow send buffer.
    // fmt_sendLog(LOG_ERROR, "decode error", 0.0F);
  }
}

// Provide stub runScanCtl handler so user can choose to not build GhostProbe.
__attribute__((weak)) void handleRunScanCtl(RunScanCtl scanCtl) {}