# Simple workflow for deploying static content to GitHub Pages
name: Build. On push-to-main, Deploy to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - 'main'
  
  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Cache ARM Toolchain
        id: cache-arm-toolchain
        uses: actions/cache@v3
        with:
          path: /opt/arm-none-eabi
          # re-install toolchain if the runner os or this file changes.
          key: arm-toolchain-${{ runner.os }}-${{ hashFiles('.github/workflows/deploy.yml') }}

      - name: Install ARM Toolchain
        if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
        run: |
          wget -q https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
          sudo tar -xf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz -C /opt
          sudo mv /opt/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi /opt/arm-none-eabi
          rm arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
      - name: Add to Path
        run: echo "/opt/arm-none-eabi/bin" >> $GITHUB_PATH
      - name: Verify Installation
        run: arm-none-eabi-gcc --version

      - name: Cmake Build
        run: . build-xmc.sh
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: example/web-ui/package-lock.json
      - name: Install node dependencies
        run: cd web-ui && npm ci
      # - name: Install python dependencies
      #   run: pip3 install --upgrade -r ../../protocol/nanopb/requirements.txt
      # - name: Install protobuf
      #   run: sudo apt update && sudo apt install -y python3-protobuf protobuf-compiler && protoc --version
      # - name: Build protobuf messages
      #   run: cd .. && source gen-proto.sh
      - name: Build UI
        run: cd web-ui && npm run build
  
  deploy:
    # Only run on pushes and manual triggers targeting the main branch. 
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./example/web-ui
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './example/web-ui/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4